In [1]:
data = open('example.txt', 'r').read()
print(data)
data_size = len(data)
print(data_size)

hello world
fuck off
jack off
29


In [5]:
vocab = list(set(data))
print(vocab)

['\n', 'c', 'u', 'a', 'j', 'w', 'd', ' ', 'h', 'r', 'l', 'f', 'e', 'o', 'k']


In [6]:
char_to_index = {ch: idx for idx, ch in enumerate(vocab)}
print(char_to_index)

{'\n': 0, 'c': 1, 'a': 3, 'j': 4, 'u': 2, 'w': 5, 'd': 6, ' ': 7, 'h': 8, 'r': 9, 'l': 10, 'e': 12, 'f': 11, 'o': 13, 'k': 14}


In [7]:
index_to_char = {idx:ch for idx, ch in enumerate(vocab)}
print(index_to_char)

{0: '\n', 1: 'c', 2: 'u', 3: 'a', 4: 'j', 5: 'w', 6: 'd', 7: ' ', 8: 'h', 9: 'r', 10: 'l', 11: 'f', 12: 'e', 13: 'o', 14: 'k'}


In [9]:
batch_size = 7
sequence_in_batch = data[0:7]
print(sequence_in_batch)
batch_of_inputs = [char_to_index[ch] for ch in data[0:7]]
print(batch_of_inputs)

hello w
[8, 12, 10, 10, 13, 7, 5]


In [10]:
import numpy as np

In [13]:
a_shape = (5, 10)
v = np.random.randn(*a_shape)
print(v)
print(v.shape)

[[-0.17669569 -1.38886693 -0.45413316  0.41283678  1.20177178  0.67960782
  -0.78053177 -3.43861033  1.85833387  0.25805631]
 [-0.1237474   0.90196055 -0.46519763 -0.12861685 -1.67132386 -1.21984655
   2.44881421 -0.84248357  0.19196002  0.20319622]
 [-2.02533941  1.13937994 -1.41230167 -0.33037942 -0.17896474 -1.30833564
  -0.23079015 -0.0387455   0.66272125  1.19151456]
 [-0.7867974  -0.43083684 -0.84853928 -0.34233434  0.14470524  1.50237181
   0.07752311 -0.37340453  0.05096408 -1.20570467]
 [ 0.72868215  1.40632391  1.60517373  0.34977921  0.53220667  1.197089
  -0.74963268 -0.14154246 -0.44917682 -1.64490911]]
(5, 10)


In [14]:
a = np.random.randint(0, 5, (5, 3))
b = np.random.randint(5, 11, (5, 3))

In [18]:
prod1 = np.dot(a.T, b)
prod2 = np.dot(b.T, a)
print(prod1,'\n', prod2)

[[71 85 68]
 [77 85 85]
 [69 84 79]] 
 [[71 77 69]
 [85 85 84]
 [68 85 79]]


In [22]:
c = np.random.randint(0, 5, (5, ))
print(c)

[4 2 1 4 0]


In [25]:
s = np.zeros((3, 5, 5))
print(s)

[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


In [26]:
a = np.random.randint(1, 6, (4, 5))
print(a)

[[1 4 3 3 1]
 [5 4 5 5 4]
 [5 5 4 5 1]
 [1 4 1 3 2]]


In [27]:
a[0]

array([1, 4, 3, 3, 1])

In [28]:
a = (0, 0, 0, 0, 0)
cache = [a for i in range(4)]
print(cache)

[(0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)]


In [29]:
cache[0] = [4, 5, 6, 7, 8]
print(cache)

[[4, 5, 6, 7, 8], (0, 0, 0, 0, 0), (0, 0, 0, 0, 0), (0, 0, 0, 0, 0)]


In [31]:
for i in range(2, -1, -1):
    print(i)

2
1
0
