In [1]:
import numpy as np

In [2]:
a = np.random.randint(100, size=(5, 3, 2, 2))
print(a)

[[[[56 34]
   [16 13]]

  [[64 26]
   [62 70]]

  [[72  2]
   [29 93]]]


 [[[35 53]
   [ 7 16]]

  [[75 49]
   [48 31]]

  [[48 19]
   [12 14]]]


 [[[98 10]
   [39 24]]

  [[15 22]
   [ 9 50]]

  [[87 90]
   [29 75]]]


 [[[ 0 53]
   [60 34]]

  [[38 84]
   [72 36]]

  [[18  0]
   [73 58]]]


 [[[29 13]
   [21 10]]

  [[ 5  8]
   [91 33]]

  [[52 18]
   [28  1]]]]


In [3]:
b = a[0]
print(b)

[[[56 34]
  [16 13]]

 [[64 26]
  [62 70]]

 [[72  2]
  [29 93]]]


In [4]:
np.max(b, axis=0)

array([[72, 34],
       [62, 93]])

In [5]:
a = np.random.randint(-5, -1, (3, 4, 4))
print(a)
print(np.abs(a))

[[[-5 -2 -2 -2]
  [-2 -5 -5 -5]
  [-3 -5 -2 -3]
  [-3 -4 -4 -2]]

 [[-3 -4 -4 -3]
  [-2 -3 -2 -4]
  [-4 -3 -4 -3]
  [-5 -5 -5 -5]]

 [[-4 -2 -3 -4]
  [-5 -2 -2 -5]
  [-5 -2 -2 -3]
  [-3 -2 -5 -3]]]
[[[5 2 2 2]
  [2 5 5 5]
  [3 5 2 3]
  [3 4 4 2]]

 [[3 4 4 3]
  [2 3 2 4]
  [4 3 4 3]
  [5 5 5 5]]

 [[4 2 3 4]
  [5 2 2 5]
  [5 2 2 3]
  [3 2 5 3]]]


In [6]:
s = np.random.randint(100, size=(1, 100))
print(s)

[[ 9 48  1 82 74 99 73 65 25 21  1 27 57 60  9  4 30 45 31 53 16 41 82 52
  57 39 40 50 34 90 58 58 16 21 84 28 82 88  5 57 77 62 75 21 63 31 97  7
  63 25 56 14 81 96 53 43 33 66 77  1 30 68 95 31 63 23 21 59 95 64 44 74
  35 73 66 53 49 50 93 78 38 36 85 10 18 60 70 47 50 18 69 35 51 86 40 38
  39 74 52 49]]


In [7]:
s[0, 67]

59

In [8]:
s[0, 2]

1

In [12]:
a = np.array([67])

In [13]:
a.shape

(1,)

In [14]:
a[0]

67